### ISSUE TITLE
Error versión de detectizr con modernizr v2.8.3

### ISSUE THREAD

**Issue by ginirsss** [juanbrujo/simple-grunt-workflow#1]
Al realizar por consola el "npm bower", da error el bower cuando carga el detectizr v2.0.0 ya que necesita la versión Modernizr v2.7.1 y no la Modernizr v2.8.3 que esta incluida en bower.json, igual da la alerta el terminal y hace la sugerencia.

**Comment by juanbrujo** [comment]
Gracias @ginirsss apenas pueda lo reviso

**Comment by juanbrujo** [comment]
@ginirsss porq entras el comando `npm bower`y no `bower install`? Lo acabo de hacer y sin problemas descargo todo. De ahi corri `grunt` e hizo todo lo q tenia q hacer, concateno Modernzr+Detectizr sin errores.

![screen shot 2015-01-23 at 16 42 59](https://cloud.githubusercontent.com/assets/362186/5881289/6c72daa8-a31e-11e4-9b09-7dfb016fd33c.png)

**Comment by juanbrujo** [comment]
cerrare esto por falta de informacion
