### ISSUE TITLE
Problemas con google maps

### ISSUE THREAD

**Issue by flacu** [juanbrujo/simple-grunt-workflow#2]
El archivo src/less/inc/html5reset.less, en las lineas 12, 13 y 14, genera un error en los controles de la esquina superior izquierda de los mapas embedidos de google maps.

![error-maps](https://cloud.githubusercontent.com/assets/5889010/6351094/7ff2ae84-bc17-11e4-8d0a-f3ff271ebb2b.jpg)

**Comment by juanbrujo** [comment]
@flacu alguna URL para revisarlu?

**Comment by flacu** [comment]
Aqui repliqué: http://codepen.io/flacu/pen/xbjjqP

**Comment by juanbrujo** [comment]
gracias @flacu el error es el HTMLReset, se los hice notar, cambiare el reset a un normalize y lo incluire en bower.json para siempre estar actualizado

**Comment by juanbrujo** [comment]
@flacu decidi remover HTML5reset.less por YUI3-cssreset el cual despues de mucho leer es el mas robusto para sitios complejos. [Nuevo push](https://github.com/juanbrujo/simple-grunt-workflow/commit/5d8444de8439a77d8e44f34d431ae06810de80e3) al master.
